### ISSUE TITLE
Timeout lost in new lambda deploy

### ISSUE THREAD

**Issue by egipros06** [amity-framework/amityjs#51]
[AMITY]

Lambda timeout set to 30 secs in function.res.json.
When deployed (via lambdaManager.updateResource), it becomes back to 3 seconds.

{
  "name": "GetXObject",
  "handler": "index.handler",
  "timeout": 30,
  "memorySize": 128,
  "eventSource": null,
  "role":"[object Object]",
  "dependencies":{
    "applications": {
      "dynamoDB": {
        "tableName":"nsXXXXXplications",
        "region": "eXXXXXt-1"
      }
    }
  }
}

**Comment by aletheia** [comment]
Fixed in 0.3.10

**Comment by egipros06** [comment]
Tested with 0.3.12, still does not work.
